// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE_ll7S47TfCqLA0gUx67qUs1tkdXwAzU',
    appId: '1:1037967421326:web:4f9724de414f59cec93edf',
    messagingSenderId: '1037967421326',
    projectId: 'romagnago-app',
    authDomain: 'romagnago-app.firebaseapp.com',
    storageBucket: 'romagnago-app.firebasestorage.app',
    measurementId: 'G-Y0H417SKMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl8a_QiPmhbK3IlhmwBQf8FcsFl121qEA',
    appId: '1:1037967421326:android:21cbc516f312bc7ec93edf',
    messagingSenderId: '1037967421326',
    projectId: 'romagnago-app',
    storageBucket: 'romagnago-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6KXmWog8eM3TlMqYzg4rl0WnBiz3h5Wo',
    appId: '1:1037967421326:ios:c02c8d9f9896bac6c93edf',
    messagingSenderId: '1037967421326',
    projectId: 'romagnago-app',
    storageBucket: 'romagnago-app.firebasestorage.app',
    iosClientId: '1037967421326-rme0tihbnt1o2lprphk6qech1ivstd8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.romagnago',
  );
}
